name: spotifydata
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.1.1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6
  url_launcher: ^5.0.2
  cupertino_icons: ^0.1.2
  #spotify_sdk:
  logger: ^0.8.0
  marquee: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Florsn
      fonts:
        - asset: fonts/Florsn02.ttf
        - asset: fonts/Florsn01.ttf
    - family: Sen
      fonts:
        - asset: fonts/Sen-Bold.ttf
        - asset: fonts/Sen-Regular.ttf
        - asset: fonts/Sen-ExtraBold.ttf
